services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    container_name: elasticsearch
    environment:
      # - 'ELASTIC_PASSWORD=admin'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
    networks:
      - common-net

  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_DATABASE=metrics'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
    networks:
      - common-net

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data
    networks:
      - common-net

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - mongodb
      - elasticsearch
      - nginx
      - app
    ports:
      - '8125:8125'
    networks:
      - common-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/datasource/default.yaml:/etc/grafana/provisioning/datasources/default.yaml
#      - ./grafana/dashboards/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
#      - ./grafana/dashboards/tig.json:/var/lib/grafana/dashboards/tig.json
    ports:
      - '3000:3000'
    networks:
      - common-net

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    ports:
      - '80:80'
    networks:
      - common-net

  app:
    image: freestl/hsa3_app
    container_name: app
    depends_on:
          - mongodb
          - elasticsearch
    ports:
      - '8081:8081'
    networks:
      - common-net

networks:
  common-net:
    driver: bridge
    name: common-net

volumes:
  influxdb-data: {}
